name: Test script on different OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
        fail-fast: false
        matrix:
            config:
                - {os: macos-12,   r: 'release'}
                - {os: ubuntu-latest, r: 'devel'}
                - {os: windows-2022, r: 'release'}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@v2
        with:
            r-version: ${{ matrix.config.r }}
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes','docopt','dplyr', 'gtools')); utils::install.packages('renv')" 
            Rscript -e "renv::restore();renv::hydrate()"
      - name: Test script
        run: Rscript entrypoint.R --data STS_dummy_data.txt --cases MRN_PCGC.txt --zip-output-tables
  
